spring.application.name=game-deploy-manager
spring.datasource.url=${JDBC_URL}
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true